# Generated by Django 6.0.4 on 2026-10-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_child_vaccinationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='completed_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vaccinations', to='accounts.hospital'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_appointments', to='accounts.hospital'),
        ),
    ]
